magic991_main:
    resource: "@Magic991MainBundle/Resources/config/routing.yml"
    prefix:   /

login:
    pattern: /login
    defaults: { _controller: Magic991SecurityBundle:Security:login }
    
login_check:
    pattern: /login_check
    
gregwar_captcha_routing:
    resource: "@GregwarCaptchaBundle/Resources/config/routing/routing.yml"
    
gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media