jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    editor:  { password: edit4YRMC, roles: [ 'ROLE_USER' ] }
                    healthtips: { password: EDIT4bhycn, roles: ['ROLE_USER'] }

    firewalls:
        yrmc_editor:
            pattern:    ^/
            anonymous: ~
            #http_basic:
                #realm: "Secured Healthy Living Editor"
            form_login:
                login_path: /login
                check_path: /login_check
            #logout:
                #path:   _demo_logout
                #target: _demo
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/yrmc, roles: ROLE_USER }
        - { path: ^/healthtips, roles: ROLE_USER }
        