parameters:
  magic.emails.contact_email: [jeff.basham@kaff.com]
  magic.emails.songrequest_email: [leza@magic991.com]
  magic.emails.advertise_email: [webmaster@magic991.com, jeff.basham@kaff.com, karen.kinney@kaff.com, clay.mccauslin@kaff.com, patrick@magic991.com]
  magic.emails.webmaster_email: webmaster@magic991.com

ivory_ck_editor:
    enable: true
    base_path: "/bundles/ivoryckeditor/"
    js_path: "/bundles/ivoryckeditor/ckeditor.js"
    configs:
        yrmc_config:
            toolbar:  "yrmc_toolbar"
            ui_color: "#ffffff"
            height: "550"
        #my_config_2:
            #toolbar:  "my_toolbar_2"
            #ui_color: "#ffffff"
    toolbars:
        configs:
            yrmc_toolbar: [ "@document", "@styles", "@color", "/", "@basicstyles", "@paragraph", "@link", "/", "@source", "@tool1", "@tool2" ]
            #my_toolbar_2: [ "@document", "/", "@tool" ]
        items:
            document: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord", "Undo", "Redo"  ]
            styles: [ "Styles", "Format", "Font", "FontSize" ]
            color: [ "TextColor", "BGColor" ]
            basicstyles: [ "Bold", "Italic", "Underline", "Strike", "Subscript", "Superscript", "-", "RemoveFormat" ]
            paragraph: [ "NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Blockquote", "CreateDiv", "-", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "-", "BidiLtr", "BidiRtl" ]
            link:     [ "Link", "Unlink" ]
            source: [ "Source" ]
            tool1:     [ "Maximize" ]
            tool2:     [ "Save" ]