parameters:
#    magic991_main.example.class: Magic991\MainBundle\Example

services:
#    magic991_main.example:
#        class: %magic991_main.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
