<?php

namespace Magic991\MainBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ConcertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConcertRepository extends EntityRepository
{
    public function getConcert()
    //$gid is above param passed in if narrowing
    {
        $qb = $this->createQueryBuilder('c')
                ->select('c')
                //->where('g.id = :gid')
                ->where('c.showKTMG = :k')
                ->andWhere('c.published = :p')
                ->addOrderBy('c.concertDate', 'ASC')
                ->setParameter('k', 1)
                ->setParameter('p', 1)
                //$qb->setMaxResults(1)
                ;
                
        return $qb->getQuery()
                       ->getResult();
    }
}
